#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: craft online shopping rest API use Basic Auth
describedBy:
  queryParameters:
    username: 
     description: username
     type: string
     required: false
     maxLength: 30
     minLength: 5
     example: alemt
    password: 
     description: password
     type: string
     required: false
     maxLength: 10
     minLength: 2
     example:  alazar
      
           
       
   
    